spring:
  datasource:
    username: root
    password: iamzjz
    url: jdbc:mysql://localhost:3306/yuequ?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&SelectMethod=cursor
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
logging:
  level:
      com.cloudtech.dao: debug